### ISSUE TITLE
Avoir un peu de marge à droite pour pouvoir déplacer un bloc à droite

### ISSUE THREAD

**Issue by louis-ev** [arnaudjuracek/pinp#2]
Par exemple ici je peux pas mettre les blocs côte à côte : 

![image](https://user-images.githubusercontent.com/1948417/59620003-13e6eb80-912c-11e9-97bf-1aef59bb820b.png)

**Comment by arnaudjuracek** [comment]
Ça devrait être faisable en CSS directement sur le container : 

```css
box-sizing: content-box;
padding-right: 100px;
```
