### ISSUE TITLE
Handle OOB

### ISSUE THREAD

**Issue by louis-ev** [arnaudjuracek/pinp#4]
Malgré `updateContainerHeight: false`, les éléments poussés peuvent sortir du container : 

![poussage_hors](https://user-images.githubusercontent.com/1948417/59620457-2ca3d100-912d-11e9-8bfe-bfaf62ffbda5.gif)

S’il y a de la place dans la direction opposé ça déplace meme tous les éléments !

**Comment by arnaudjuracek** [comment]
C'est le comportement désiré losque `updateContainerHeight: false` : le container ne change pas de hauteur, donc les éléments sortent par le bas.

Pour l'instant la seule façon de régler le problème est avec ce jeu d'options : 
```js
{
  updateContainerHeight: false,
  updateContainerWidth: true,
  pushBehavior: 'horizontal'
}
```
… ce qui aura pour effet de bloquer la sortie par le bas (les blocs ne peuvent être poussés que sur les côtés).

Dans une seconde version, le problème pourra être réglé en améliorant le comportement de poussage des blocs.

**Comment by arnaudjuracek** [comment]
Fix in 54cfc444fe99f154dc7301560b3e5b77b2b1dacd
